package io.github.valentinkarnaukhov.stubgen.codegen.java;

import io.github.valentinkarnaukhov.stubgen.spec.TypeRef;
import io.github.valentinkarnaukhov.stubgen.target.TargetOptions;

import java.util.Optional;

/**
 * Maps a specification type onto the Java type a stub should use.
 *
 * <p>These choices are not free. The stubs sit beside a client generated by
 * openapi-generator from the same specification, and a caller passes values back and
 * forth between the two. Whenever this mapping disagrees with theirs, the caller converts
 * by hand — so the rule is to follow openapi-generator's Java defaults rather than pick
 * what reads best in isolation.
 */
final class JavaTypes {

    private final TargetOptions options;

    JavaTypes(TargetOptions options) {
        this.options = options;
    }

    /**
     * The type a value of this shape is written as, or empty when it cannot be named.
     *
     * <p>Empty happens for an object or enum when no model package is configured. There is
     * nothing to fall back to: this generator does not emit models, on purpose, so the
     * only name for {@code CompositeBody} is the consumer's own.
     */
    Optional<String> nameOf(TypeRef type) {
        return switch (type.kind()) {
            case PRIMITIVE -> Optional.of(primitive(type.openApiType(), type.format()));
            case OBJECT -> options.modelPackageIfPresent().map(pkg -> pkg + "." + type.schemaName());
            case ENUM -> options.modelPackageIfPresent().map(pkg -> type.declaringSchema() == null
                    ? pkg + "." + type.schemaName()
                    : pkg + "." + type.declaringSchema() + "$" + type.schemaName());
            case ARRAY -> nameOf(type.items()).map(item -> "java.util.List<" + item + ">");
            case MAP -> nameOf(type.items()).map(value -> "java.util.Map<java.lang.String, " + value + ">");
            case UNKNOWN -> Optional.of("java.lang.Object");
        };
    }

    /** The model type a schema is named by, which exists only if a model package was set. */
    String modelType(String schemaName) {
        return options.modelPackageIfPresent()
                .map(pkg -> pkg + "." + schemaName)
                .orElseThrow(() -> new IllegalStateException(
                        "no model package configured, so " + schemaName + " cannot be named"));
    }

    private static String primitive(String openApiType, String format) {
        String type = openApiType == null ? "string" : openApiType;
        String fmt = format == null ? "" : format;
        return switch (type) {
            case "integer" -> "int64".equals(fmt) ? "java.lang.Long" : "java.lang.Integer";
            case "number" -> switch (fmt) {
                case "float" -> "java.lang.Float";
                case "double" -> "java.lang.Double";
                // openapi-generator's Java default for a bare number. Picking Double here
                // instead would look tidier and quietly disagree with the caller's client.
                default -> "java.math.BigDecimal";
            };
            case "boolean" -> "java.lang.Boolean";
            case "string" -> switch (fmt) {
                case "date" -> "java.time.LocalDate";
                case "date-time" -> "java.time.OffsetDateTime";
                case "uuid" -> "java.util.UUID";
                default -> "java.lang.String";
            };
            default -> "java.lang.String";
        };
    }

    /**
     * Renders a parameter value as the string an HTTP request actually carries.
     *
     * <p>Everything on the wire is text. The typed signature exists so the compiler checks
     * the call, not because the value stays typed — which is why a String parameter is
     * passed straight through and everything else goes via {@code String.valueOf}.
     */
    static String asQueryValue(String javaType, String expression) {
        return "java.lang.String".equals(javaType) ? expression : "String.valueOf(" + expression + ")";
    }
}
