package com.example.stubs.postbyrequestbodycomposite;

import com.example.model.CompositeBody;
import com.github.tomakehurst.wiremock.client.MappingBuilder;
import com.github.tomakehurst.wiremock.matching.StringValuePattern;
import io.github.valentinkarnaukhov.stubgen.runtime.AbstractStub;
import io.github.valentinkarnaukhov.stubgen.runtime.StubTarget;

import static com.github.tomakehurst.wiremock.client.WireMock.equalToJson;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo;

/**
 * GOLDEN REFERENCE — hand-written specification of the generator's output.
 * Source: sample-api.yaml, operation postByRequestBodyComposite.
 *
 * <p>Demonstrates: a request body that references a component schema.
 */
public final class PostByRequestBodyCompositeStub extends AbstractStub<PostByRequestBodyCompositeStub> {

    private static final String PATH = "/post/request-body/composite";

    private StringValuePattern bodyPattern;

    public PostByRequestBodyCompositeStub(StubTarget target) {
        super(target);
    }

    /**
     * The model type comes from the consumer's own client, generated by
     * openapi-generator. We only reference it — see the modelPackage option.
     */
    public PostByRequestBodyCompositeStub body(CompositeBody body) {
        this.bodyPattern = equalToJson(serialize(body));
        return self();
    }

    /** 200 declares no content, so the method takes no body. */
    public PostByRequestBodyCompositeStub code200() {
        return response(200, null);
    }

    @Override
    protected MappingBuilder toRequest() {
        MappingBuilder request = post(urlPathEqualTo(PATH));
        if (bodyPattern != null) {
            request.withRequestBody(bodyPattern);
        }
        return request;
    }

    // ── OPEN QUESTION ─────────────────────────────────────────────────────────
    //
    // Serialisation. serialize(body) is AbstractStub's, so the request matcher and
    // the response body go through one mapper — the alternative is a stub that
    // reads and writes JSON in two different dialects. Which mapper that should be
    // is still open:
    //   - the default delegates to WireMock's own Json, whose configuration is not
    //     ours and need not match the consumer's client;
    //   - the consumer's models carry Jackson annotations from openapi-generator
    //     (date formats, @JsonInclude, naming) that a foreign mapper will not
    //     honour, producing a body the client would never send;
    //   - and wiremock-standalone relocates Jackson, so under that artifact the
    //     default cannot see those annotations at all.
    // Overriding serialize is the escape hatch today; a first-class hook is owed.
    //
    // No pattern overload for the body either — same call as for parameters, see
    // GetByInQueryParametersStub. The body is matched by equalToJson and nothing
    // else; a looser match goes through customize(b -> b.withRequestBody(...)).
    // Note this one is more awkward to defer than the parameter case: equalToJson
    // compares the whole document, so "any request whose id is 5" has no
    // expression here at all.
    //
    // For the list variant the only difference is the parameter type:
    // body(List<CompositeBody>). Mechanical, no new decisions.
    //
    // For the primitive variant the parameter is body(String), and equalToJson is
    // wrong there: a bare string body is not JSON. The emitter must pick the
    // matcher from the schema kind, not apply equalToJson unconditionally.
    // ──────────────────────────────────────────────────────────────────────────
}
