package com.example.stubs.postbyrequestbodycomposite;

import com.example.model.CompositeBody;
import com.github.tomakehurst.wiremock.client.MappingBuilder;
import io.github.valentinkarnaukhov.stubgen.runtime.AbstractRequestBodyMatcher;
import io.github.valentinkarnaukhov.stubgen.runtime.AbstractStub;
import io.github.valentinkarnaukhov.stubgen.runtime.StubTarget;

import static com.github.tomakehurst.wiremock.client.WireMock.equalTo;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo;

/**
 * GOLDEN REFERENCE — hand-written specification of the generator's output.
 * Source: sample-api.yaml, operation postByRequestBodyComposite.
 *
 * <p>Demonstrates: a request body constrained through nested matchers, mirroring the
 * way a response body is described.
 *
 * <p>Reads as:
 *
 * <pre>{@code
 * new PostByRequestBodyCompositeStub(target)
 *         .requestBody()
 *             .primitive("FIRST")
 *             .compositeDeepFieldDeepestField("DEEP")
 *             .compositeList().innerField("A")
 *         .mock();
 * }</pre>
 */
public final class PostByRequestBodyCompositeStub extends AbstractStub<PostByRequestBodyCompositeStub> {

    private static final String PATH = "/post/request-body/composite";

    public PostByRequestBodyCompositeStub(StubTarget target) {
        super(target);
    }

    /**
     * Matches a request whose body equals this object as JSON. The model type comes
     * from the consumer's own client, generated by openapi-generator — we only
     * reference it, see the modelPackage option.
     *
     * <p>Named requestBody rather than body: on a stub it stands next to codeNNN(),
     * which says which direction it describes, and body() would not. The accessors
     * inside the matcher stay symmetric with the response builder's — that is where
     * reading the same schema the same way on both sides pays.
     */
    public PostByRequestBodyCompositeStub requestBody(CompositeBody body) {
        return matchWholeRequestBody(body);
    }

    /**
     * Constrains the request body field by field. Partial by construction, which is
     * what the whole-document form above cannot be.
     */
    public CompositeBodyMatcher<PostByRequestBodyCompositeStub> requestBody() {
        return new CompositeBodyMatcher<>(this, "$");
    }

    /** 200 declares no content, so the method takes no body and returns no builder. */
    public PostByRequestBodyCompositeStub code200() {
        return response(200, null);
    }

    @Override
    protected MappingBuilder toRequest() {
        return post(urlPathEqualTo(PATH));
    }

    // ── REQUEST BODY MATCHERS ─────────────────────────────────────────────────
    //
    // Inner classes for the same reason the body builders are: one operation, one
    // file. Being inner also removes the plumbing — the matcher reaches
    // addRequestBodyPattern through the enclosing instance, so that method stays
    // protected and the raw WireMock surface is never reopened.
    //
    // A matcher carries the JSONPath it is rooted at instead of baking it into the
    // method names, which is why one class covers both the body itself and the
    // elements of a nested list.

    public final class CompositeBodyMatcher<P> extends AbstractRequestBodyMatcher<P> {

        CompositeBodyMatcher(P parent, String path) {
            super(parent, PostByRequestBodyCompositeStub.this, path,
                    PostByRequestBodyCompositeStub.this::addRequestBodyPattern);
        }

        public CompositeBodyMatcher<P> primitive(String value) {
            match(".primitive", equalTo(value));
            return this;
        }

        public CompositeBodyMatcher<P> compositeInnerField(String value) {
            match(".composite.innerField", equalTo(value));
            return this;
        }

        public CompositeBodyMatcher<P> compositeDeepFieldDeepestField(String value) {
            match(".composite.deepField.deepestField", equalTo(value));
            return this;
        }

        /**
         * A list of primitives has nothing inside it to reach for, so the question
         * is whether any element equals the value. Equality against the whole list
         * is a different question, and requestBody(...) already answers it.
         */
        public CompositeBodyMatcher<P> primitiveList(String value) {
            match(".primitiveList[?(@ == '" + value + "')]");
            return this;
        }

        /**
         * Descends into the elements of a list of objects. There is no addNew() and
         * there cannot be: matching does not create anything. [*] means any element,
         * so this matches a request where at least one element qualifies — the
         * mirror of the builder's addNew(), and not its equal.
         */
        public CompositeFieldMatcher<CompositeBodyMatcher<P>> compositeList() {
            return new CompositeFieldMatcher<>(this, path() + ".compositeList[*]");
        }
    }

    public final class CompositeFieldMatcher<P> extends AbstractRequestBodyMatcher<P> {

        CompositeFieldMatcher(P parent, String path) {
            super(parent, PostByRequestBodyCompositeStub.this, path,
                    PostByRequestBodyCompositeStub.this::addRequestBodyPattern);
        }

        public CompositeFieldMatcher<P> innerField(String value) {
            match(".innerField", equalTo(value));
            return this;
        }

        public CompositeFieldMatcher<P> deepFieldDeepestField(String value) {
            match(".deepField.deepestField", equalTo(value));
            return this;
        }
    }

    // ── THE TWO ENDS OF A STUB NOW READ ALIKE ─────────────────────────────────
    //
    // requestBody() and codeNNN() hand out builders over the same schema with the same
    // method names. That is why the request prefix could go from the accessors: an
    // earlier draft put requestCompositeInnerField and response200CompositeInnerField
    // on this one class, where they would otherwise have had identical signatures.
    // Neither name shares a namespace with the other any more.
    //
    // The prefix stays on the entry point, though. Symmetry is worth having between
    // things that read the same, and the two entry points do not: codeNNN() names its
    // direction and a bare body() would name nothing, leaving the reader to infer
    // "request" from the absence of a status code. An earlier draft dropped the prefix
    // everywhere and made exactly that mistake.
    //
    // The symmetry is in the names only. Underneath, a body builder constructs an
    // object and a matcher appends a JSONPath expression; there is no lazy creation
    // here, because a matcher has nothing to create. The one place the difference
    // surfaces is lists, where the builder has addNew() and the matcher has [*].
    //
    // SETTLED — PARTIAL MATCHING IS BACK.
    // Dropping the StringValuePattern overload on requestBody(...) removed the only way to
    // say "any request whose composite.innerField is x", since equalToJson compares
    // the whole document. The matcher restores it, and does so without naming the
    // field as a string.
    //
    // SETTLED — WHY THERE IS NO equalTo ON THE MATCHER.
    // Moving the whole-document form off the stub and onto the matcher would give one
    // entry point instead of an overloaded pair, and it does not work. Verified
    // against WireMock: a value pattern on a path ending in [*] is applied to the
    // entire selection rendered as an array, not to each element, so
    // matchingJsonPath("$.compositeList[*]", equalToJson(oneElement)) does not match a
    // document that contains that element, while equalToJson(theWholeList) does.
    // A matcher class serves every position its schema occupies, and the only nested
    // positions this design creates are list elements — precisely where the method
    // would read as "some element equals this" and mean "the whole list equals this".
    // Varying the signature by position is what D15 already rejected.
    //
    // OPEN — CONDITIONS ON THE SAME ELEMENT.
    // compositeList().innerField("A").deepFieldDeepestField("B") emits two
    // independent matchers, so a request whose first element carries A and whose
    // second carries B matches. Asking for one element carrying both needs a single
    // filter — $.compositeList[?(@.innerField == 'A' && …)] — which this shape
    // cannot build, because each call has already been sent to the stub.
    // The filter form itself is confirmed to work, so the obstacle is when the
    // expression is assembled, not whether WireMock understands it.
    //
    // OPEN — ESCAPING.
    // primitiveList interpolates the value into the filter expression, so a quote
    // in the value breaks it. The others pass the value to equalTo, which does not
    // parse it.
    //
    // OPEN — SERIALISATION.
    // serialize(body) is AbstractStub's, so the request matcher and the response
    // body go through one mapper — the alternative is a stub that reads and writes
    // JSON in two dialects. Which mapper is still undecided:
    //   - the default delegates to WireMock's own Json, whose configuration is not
    //     ours and need not match the consumer's client;
    //   - the consumer's models carry Jackson annotations from openapi-generator
    //     (date formats, @JsonInclude, naming) that a foreign mapper will not
    //     honour, producing a body the client would never send;
    //   - and wiremock-standalone relocates Jackson, so under that artifact the
    //     default cannot see those annotations at all.
    // Overriding serialize is the escape hatch today; a first-class hook is owed.
    //
    // OPEN — NON-OBJECT REQUEST BODIES.
    // For a list body the matcher would be rooted at $[*] and requestBody(...) would take
    // List<CompositeBody> — mechanical. For a bare string body equalToJson is simply
    // wrong, and there is nothing to build a matcher over. The emitter must pick
    // from the schema kind rather than assume JSON objects.
    // ──────────────────────────────────────────────────────────────────────────
}
