package io.github.valentinkarnaukhov.wiremockstubgen.openapi;

import io.github.valentinkarnaukhov.wiremockstubgen.naming.Identifiers;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.ObjectSchema;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Property;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.TypeRef;
import io.swagger.v3.oas.models.media.Schema;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.function.Consumer;

/**
 * The schemas of one document, resolved into something a stub can be built from.
 *
 * <p>Separate from {@link OpenApiReader} because resolving a schema is not reading a
 * document: it has to invent names, merge compositions and register things the document
 * never declared, and it has to do so while being walked. Keeping that state here leaves
 * the reader as a traversal.
 *
 * <p>Two rules below are not ours to choose, and neither was guessed. Generated stubs
 * reference the model classes openapi-generator writes, so wherever it invents a type this
 * has to invent the same name, and wherever it merges a composition this has to merge it
 * the same way. Both were read off models generated by openapi-generator 7.9.0 and 7.24.0,
 * which agree:
 *
 * <ul>
 *   <li><b>Composition is flattened.</b> {@code allOf} of two references produces one
 *       class holding every property of both, in member order — not a subclass. Members
 *       may themselves be compositions.</li>
 *   <li><b>An inline object is named after where it sits.</b> Property {@code inner} of
 *       schema {@code Nested} becomes {@code NestedInner}; the response body of
 *       {@code postInlineRoot} at 200 becomes {@code PostInlineRoot200Response}, its
 *       property {@code origin} becomes {@code PostInlineRoot200ResponseOrigin}, and the
 *       element type of an array becomes that name plus {@code Inner}.</li>
 * </ul>
 */
final class Schemas {

    private final Map<String, Schema> declared;

    private final Map<String, ObjectSchema> resolved = new LinkedHashMap<>();

    private final Consumer<String> warnings;

    private final Composition composition;

    Schemas(Map<String, Schema> declared, Consumer<String> warnings, Composition composition) {
        this.declared = Objects.requireNonNull(declared, "declared");
        this.warnings = Objects.requireNonNull(warnings, "warnings");
        this.composition = Objects.requireNonNull(composition, "composition");
    }

    /**
     * Resolves every schema the document declares.
     *
     * <p>Runs before the operations are read so that a body referring to a schema finds it
     * already there. Bodies may still add to the map afterwards, since an inline body is a
     * schema the document does not declare.
     */
    void readDeclared() {
        declared.forEach(this::register);
    }

    Map<String, ObjectSchema> resolved() {
        return Map.copyOf(resolved);
    }

    /**
     * Turns a schema into a type reference.
     *
     * @param nameHint what an inline object here would be called. Null where there is no
     *                 sensible name, in which case an inline object is reported and
     *                 dropped rather than named badly.
     */
    TypeRef typeOf(Schema<?> schema, String nameHint) {
        return typeOf(schema, nameHint, null);
    }

    /**
     * @param objectName what an inline object here would be called
     * @param enumName   what an inline enum here would be called, as
     *                   {@code Owner.MemberEnum}. Unlike the object name this does not
     *                   change as an array is entered: an enum written as the items of
     *                   property {@code many} is called {@code ManyEnum}, not
     *                   {@code ManyInnerEnum}.
     */
    private TypeRef typeOf(Schema<?> schema, String objectName, String enumName) {
        if (schema == null) {
            return TypeRef.unknown();
        }
        if (schema.get$ref() != null) {
            return referenced(schema.get$ref(), new LinkedHashSet<>());
        }
        if ("array".equals(schema.getType()) || schema.getItems() != null) {
            return TypeRef.array(typeOf(schema.getItems(), element(objectName), enumName));
        }
        if (schema.getAdditionalProperties() instanceof Schema<?> values) {
            return TypeRef.map(typeOf(values, objectName, enumName));
        }
        if (schema.getProperties() != null || schema.getAllOf() != null || merging(schema)) {
            // An allOf wrapping one reference and adding nothing of its own is not a type,
            // it is that reference. Specifications write it constantly, to hang a
            // description or a readOnly flag on a $ref, which JSON Schema does not otherwise
            // allow. openapi-generator resolves it to the referenced class and writes no new
            // one — verified on 7.24.0, where a second member, or properties alongside the
            // reference, does produce one.
            List<Schema> members = schema.getAllOf();
            if (schema.getProperties() == null && members != null && members.size() == 1
                    && members.get(0).get$ref() != null) {
                return referenced(members.get(0).get$ref(), new LinkedHashSet<>());
            }
            String alias = alternativeAlias(schema);
            if (alias != null) {
                return referenced(alias, new LinkedHashSet<>());
            }
            return inline(schema, objectName);
        }
        if (schema.getEnum() != null && enumName != null) {
            int separator = enumName.indexOf('.');
            return TypeRef.nestedEnumeration(
                    enumName.substring(0, separator), enumName.substring(separator + 1));
        }
        if (schema.getOneOf() != null || schema.getAnyOf() != null) {
            // Only reachable under OPAQUE; merging sends these to inline() above.
            warnings.accept(describe(objectName) + " is composed with oneOf or anyOf, which"
                    + " is being read as opaque; the stub will take the body whole and offer"
                    + " no accessors into it");
            return TypeRef.unknown();
        }
        if (schema.getType() == null || "object".equals(schema.getType())) {
            // An object with nothing in it describes no shape, and openapi-generator
            // passes it through as Object rather than writing a class for it.
            return TypeRef.unknown();
        }
        // An inline enum in a position that gives it no name — a parameter, or the whole
        // body — is deliberately read as its base type. Nothing generates a class for one
        // of those, so naming a type here would leave the stub the only place that has it.
        return TypeRef.primitive(schema.getType(), schema.getFormat());
    }

    /**
     * Resolves a reference to what the referenced schema actually is.
     *
     * <p>Not every name a specification declares becomes a class. openapi-generator writes
     * a model only for schemas that have a shape of their own — properties, a composition,
     * or an enum. A name given to a boolean, or to an array of something else, is an alias:
     * the generator writes {@code Boolean} and {@code List<RolloutPartnerV3>} straight into
     * the signatures and no class by that name ever exists. Naming the class here anyway is
     * how a stub stops compiling, and one real specification of 93 schemas had thirteen
     * such aliases.
     *
     * @param visiting guards a chain of aliases that refers back into itself.
     */
    private TypeRef referenced(String ref, Set<String> visiting) {
        String name = referencedName(ref);
        if (name == null) {
            warnings.accept("Ignoring the unsupported reference " + ref);
            return TypeRef.unknown();
        }
        Schema<?> target = declared.get(name);
        if (target == null) {
            warnings.accept("Ignoring the dangling reference " + ref);
            return TypeRef.unknown();
        }
        if (target.getEnum() != null) {
            return TypeRef.enumeration(name);
        }
        String alias = alternativeAlias(target);
        if (alias != null) {
            if (!visiting.add(name)) {
                warnings.accept("Schema " + name + " is an alias for itself; ignoring it");
                return TypeRef.unknown();
            }
            return referenced(alias, visiting);
        }
        if (hasShapeOfItsOwn(target)) {
            return TypeRef.object(name);
        }
        if (target.get$ref() != null) {
            if (!visiting.add(name)) {
                warnings.accept("Schema " + name + " is an alias for itself; ignoring it");
                return TypeRef.unknown();
            }
            return referenced(target.get$ref(), visiting);
        }
        return typeOf(target, null, null);
    }

    private boolean hasShapeOfItsOwn(Schema<?> schema) {
        return schema.getProperties() != null
                || schema.getAllOf() != null
                || schema.getOneOf() != null
                || schema.getAnyOf() != null;
    }

    /**
     * Whether this schema's {@code oneOf} or {@code anyOf} members are to be folded in.
     */
    private boolean merging(Schema<?> schema) {
        return composition == Composition.MERGE
                && (schema.getOneOf() != null || schema.getAnyOf() != null);
    }

    /**
     * The reference a {@code oneOf} or {@code anyOf} of exactly one member stands for.
     *
     * <p>Such a composition names one alternative and so has that alternative's shape.
     * Specifications write it to hang a discriminator on a hierarchy that currently has a
     * single subtype, and it was two of the three occurrences of the keyword across 43 real
     * documents.
     *
     * <p>The two generator versions disagree about it: 7.9.0 writes a flattened class of
     * its own, 7.24.0 writes none and resolves it to the member — the same treatment
     * {@code allOf} of a single reference has always had. Reading it as the member is what
     * breaks the tie, because it is the only reading that compiles under both: 7.9.0 emits
     * the member class as well, while the flattened name exists in 7.9.0 alone.
     *
     * @return null if this is not such a composition
     */
    private String alternativeAlias(Schema<?> schema) {
        if (!merging(schema) || schema.getProperties() != null || schema.getAllOf() != null) {
            return null;
        }
        List<Schema> members = alternatives(schema);
        return members.size() == 1 ? members.get(0).get$ref() : null;
    }

    static String referencedName(String ref) {
        if (!ref.startsWith("#/components/schemas/") && !ref.startsWith("#/definitions/")) {
            return null;
        }
        return ref.substring(ref.lastIndexOf('/') + 1);
    }

    /**
     * Registers an object the document wrote out in place rather than declaring.
     *
     * <p>The name is the whole point. openapi-generator will generate a model class for
     * this same inline schema, and the stub has to name that class; inventing a name of
     * our own is how the two drift apart.
     */
    private TypeRef inline(Schema<?> schema, String nameHint) {
        if (nameHint == null || nameHint.isBlank()) {
            warnings.accept("Ignoring an inline object in a position that gives it no name");
            return TypeRef.unknown();
        }
        String name = Identifiers.pascalJoin(nameHint);
        if (declared.containsKey(name)) {
            warnings.accept("An inline object would be called " + name + ", which the"
                    + " specification already declares; taking the body whole instead");
            return TypeRef.unknown();
        }
        register(name, schema);
        return resolved.containsKey(name) ? TypeRef.object(name) : TypeRef.unknown();
    }

    private String element(String objectName) {
        return objectName == null ? null : objectName + "Inner";
    }

    // ── REGISTRATION ──────────────────────────────────────────────────────────

    private void register(String name, Schema<?> schema) {
        if (resolved.containsKey(name)) {
            return;
        }
        if (alternativeAlias(schema) != null) {
            // Nothing to register: the generator writes no class for it, and one declared
            // here would be a name the stub could refer to and nothing could satisfy.
            return;
        }
        Merged merged = merge(schema, new LinkedHashSet<>());
        if (merged.properties.isEmpty()) {
            reportUndescribable(name, schema);
            return;
        }
        // Placed before the properties are read so that a schema reaching itself finds a
        // registration in progress rather than recursing. What lands there is replaced
        // below; nothing reads it in between, because typeOf only records a name.
        resolved.put(name, new ObjectSchema(name, List.of()));

        List<Property> properties = new ArrayList<>();
        merged.properties.forEach((propertyName, propertySchema) -> properties.add(new Property(
                propertyName,
                typeOf(propertySchema,
                        Identifiers.pascalJoin(name, propertyName),
                        name + "." + Identifiers.pascalJoin(propertyName) + "Enum"),
                merged.required.contains(propertyName),
                readOnly(propertySchema, new LinkedHashSet<>()))));
        resolved.put(name, new ObjectSchema(name, properties));
    }

    /**
     * Whether only a server ever sends this property.
     *
     * <p>Follows references, because a specification may say it once by naming a schema
     * {@code readOnly} and then pointing several properties at it. openapi-generator honours
     * that — verified on 7.24.0, where a property referring to a read-only schema lost its
     * setter exactly as an inline one does — and a stub that missed it would not compile.
     */
    private boolean readOnly(Schema<?> schema, Set<String> visiting) {
        if (schema == null) {
            return false;
        }
        if (Boolean.TRUE.equals(schema.getReadOnly())) {
            return true;
        }
        if (schema.get$ref() == null) {
            return false;
        }
        String name = referencedName(schema.get$ref());
        return name != null && visiting.add(name) && readOnly(declared.get(name), visiting);
    }

    /**
     * Says out loud that a schema will have no accessors, unless it plainly never could.
     *
     * <p>An enum or a string alias has nothing to describe and is silent. A composition
     * this cannot merge, or an object declared with no properties at all, is a stub the
     * user will find poorer than expected, and finding out by reading the generated code
     * is the wrong way round.
     */
    private void reportUndescribable(String name, Schema<?> schema) {
        if (schema.getEnum() != null) {
            return;
        }
        if (composition == Composition.OPAQUE
                && (schema.getOneOf() != null || schema.getAnyOf() != null)) {
            warnings.accept("Schema " + name + " is composed with oneOf or anyOf, which is"
                    + " being read as opaque; stubs will take bodies of this type whole and"
                    + " offer no accessors into them");
            return;
        }
        if (hasShapeOfItsOwn(schema)) {
            warnings.accept("Schema " + name + " resolved to no properties at all;"
                    + " stubs will take bodies of this type whole");
        }
    }

    /**
     * Flattens a composition into one property list.
     *
     * <p>{@code allOf} members are merged in the order they are written, and a member may
     * be a composition itself. A property declared twice keeps the position of its first
     * declaration and the definition of its last, which is what merging two schemas that
     * agree about a field has to mean — and, where they disagree, is also what
     * openapi-generator settles on.
     *
     * <p>{@code oneOf} and {@code anyOf} members are folded in the same way when
     * {@link Composition#MERGE} is in force, after the {@code allOf} members and before the
     * schema's own properties.
     *
     * @param visiting guards composition cycles. Unlike {@link #typeOf}, which stops at
     *                 a name, this one follows references, so a specification composing
     *                 two schemas out of each other would otherwise not terminate.
     */
    private Merged merge(Schema<?> schema, Set<String> visiting) {
        Merged merged = new Merged();
        if (schema.getAllOf() != null) {
            for (Schema<?> member : schema.getAllOf()) {
                merged.addAll(memberOf(member, visiting));
            }
        }
        if (merging(schema)) {
            for (Schema<?> member : alternatives(schema)) {
                merged.addAll(memberOf(member, visiting));
            }
        }
        if (schema.getProperties() != null) {
            schema.getProperties().forEach((key, value) ->
                    merged.properties.put(String.valueOf(key), (Schema<?>) value));
        }
        if (schema.getRequired() != null) {
            merged.required.addAll(schema.getRequired());
        }
        return merged;
    }

    /**
     * The members of a {@code oneOf} or {@code anyOf}, in the order they are written.
     *
     * <p>A schema may legally write both, and folding both is the only reading that does
     * not silently drop half of what was said.
     */
    private List<Schema> alternatives(Schema<?> schema) {
        List<Schema> members = new ArrayList<>();
        if (schema.getOneOf() != null) {
            members.addAll(schema.getOneOf());
        }
        if (schema.getAnyOf() != null) {
            members.addAll(schema.getAnyOf());
        }
        return members;
    }

    private Merged memberOf(Schema<?> member, Set<String> visiting) {        if (member.get$ref() == null) {
            return merge(member, visiting);
        }
        String name = referencedName(member.get$ref());
        if (name == null || !declared.containsKey(name)) {
            warnings.accept("Ignoring the composition member " + member.get$ref()
                    + ", which does not resolve");
            return new Merged();
        }
        if (!visiting.add(name)) {
            warnings.accept("Schema " + name + " takes part in a cycle of composition"
                    + " members; stopping there");
            return new Merged();
        }
        Merged merged = merge(declared.get(name), visiting);
        visiting.remove(name);
        return merged;
    }

    private String describe(String nameHint) {
        return nameHint == null ? "A body" : "Schema " + nameHint;
    }

    private static final class Merged {

        private final Map<String, Schema<?>> properties = new LinkedHashMap<>();

        private final Set<String> required = new LinkedHashSet<>();

        void addAll(Merged other) {
            properties.putAll(other.properties);
            required.addAll(other.required);
        }
    }
}
