package com.example.stubs;

import com.example.model.CompositeBody;
import com.github.tomakehurst.wiremock.client.MappingBuilder;
import com.github.tomakehurst.wiremock.matching.StringValuePattern;
import io.github.valentinkarnaukhov.stubgen.runtime.AbstractStub;
import io.github.valentinkarnaukhov.stubgen.runtime.StubTarget;

import java.util.List;

import static com.github.tomakehurst.wiremock.client.WireMock.aResponse;
import static com.github.tomakehurst.wiremock.client.WireMock.equalToJson;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.urlPathEqualTo;

/**
 * GOLDEN REFERENCE — hand-written specification of the generator's output.
 * Source: sample-api.yaml, tag post-by-request-body-composite.
 *
 * <p>Demonstrates: a request body that references a component schema.
 */
public final class PostByRequestBodyCompositeStub {

    private final StubTarget target;

    public PostByRequestBodyCompositeStub(StubTarget target) {
        this.target = target;
    }

    public PostByRequestBodyComposite postByRequestBodyComposite() {
        return new PostByRequestBodyComposite(target);
    }

    public static final class PostByRequestBodyComposite extends AbstractStub<PostByRequestBodyComposite> {

        private static final String PATH = "/post/request-body/composite";

        private StringValuePattern bodyPattern;
        private int status = 200;

        public PostByRequestBodyComposite(StubTarget target) {
            super(target);
        }

        /**
         * The model type comes from the consumer's own client, generated by
         * openapi-generator. We only reference it — see the modelPackage option.
         */
        public PostByRequestBodyComposite body(CompositeBody body) {
            this.bodyPattern = equalToJson(Json.write(body));
            return self();
        }

        public PostByRequestBodyComposite body(StringValuePattern bodyPattern) {
            this.bodyPattern = bodyPattern;
            return self();
        }

        public PostByRequestBodyComposite code200() {
            this.status = 200;
            return self();
        }

        /** Status codes the specification does not declare, for negative testing. */
        public PostByRequestBodyComposite code(int status) {
            this.status = status;
            return self();
        }

        @Override
        protected MappingBuilder toMappingBuilder() {
            MappingBuilder mappingBuilder = post(urlPathEqualTo(PATH));
            if (bodyPattern != null) {
                mappingBuilder.withRequestBody(bodyPattern);
            }
            return mappingBuilder.willReturn(aResponse().withStatus(status));
        }
    }

    // ── OPEN QUESTION ─────────────────────────────────────────────────────────
    //
    // Serialisation. Json.write(body) above is a placeholder. Whose ObjectMapper?
    //   - WireMock ships com.github.tomakehurst.wiremock.common.Json, but its
    //     configuration is not ours and may not match the consumer's client.
    //   - The consumer's models carry Jackson annotations from openapi-generator
    //     (date formats, @JsonInclude, naming); serialising with a different
    //     mapper produces a body that will not match what the client sends.
    //   - Likeliest answer: a mapper supplied through StubTarget or a runtime
    //     hook, defaulting to a sane one. This is a runtime concern, so it is
    //     recorded here and deferred.
    //
    // For the list variant (postByRequestBodyCompositeList) the only difference
    // is the parameter type: body(List<CompositeBody>). Mechanical, no new
    // decisions — hence not written out as a separate golden file.
    //
    // For the primitive variant the parameter is body(String), and equalToJson
    // is wrong there: a bare string body is not JSON. The emitter must pick the
    // matcher from the schema kind, not apply equalToJson unconditionally.
    // ──────────────────────────────────────────────────────────────────────────
}
