package io.github.valentinkarnaukhov.wiremockstubgen.openapi;

import io.github.valentinkarnaukhov.wiremockstubgen.fixtures.Fixtures;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.CollectionFormat;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.ObjectSchema;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Operation;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Parameter;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.ParameterLocation;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Property;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.StubApi;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.TypeRef;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Checks the reader against a specification written the way large real ones are.
 *
 * <p>Every expectation here was read off models generated by openapi-generator 7.9.0 and
 * 7.24.0, which agree. A stub names the classes that generator writes, so a rule this
 * reader gets wrong does not produce a worse stub, it produces one that does not compile.
 */
class OpenApiCompositionTest {

    private static StubApi api;
    private static List<String> warnings;

    @BeforeAll
    static void readFixture() {
        warnings = new ArrayList<>();
        api = new OpenApiReader(warnings::add).read(Fixtures.compositionApi());
    }

    @Test
    void readsTheWholeDocumentComplainingOnlyWhereItShould() {
        assertThat(api.operations()).hasSize(10);
        // The one thing here that genuinely describes no shape is the anyOf of scalars,
        // and the one response honestly declared as something other than JSON.
        assertThat(warnings).hasSize(2);
        assertThat(warnings).anySatisfy(warning -> assertThat(warning)
                .contains("Any", "resolved to no properties at all"));
        assertThat(warnings).anySatisfy(warning -> assertThat(warning)
                .contains("getMediaTypes", "text/plain", "will still treat as JSON"));
    }

    @Test
    void carriesTheMediaTypeAResponseWasDeclaredWithRatherThanAssumingJson() {
        // A vendor JSON type still counts as JSON for matching and building the body --
        // there is nowhere else for it to come from -- but the header the stub answers
        // with must say what the specification wrote, so both are carried through.
        assertThat(responseOf("getMediaTypes", 200).mediaType()).isEqualTo("application/vnd.library.v1+json");
        assertThat(responseOf("getMediaTypes", 202).mediaType()).isEqualTo("text/plain");

        // The ordinary case, unaffected: a response declared as exactly application/json
        // still says so, so the emitter can tell the two apart without repeating the
        // reader's fallback logic.
        assertThat(responseOf("getAliases", 200).mediaType()).isEqualTo("application/json");
    }

    // ── allOf ─────────────────────────────────────────────────────────────────

    @Test
    void flattensAllOfIntoOneSchemaInMemberOrder() {
        // Not a subclass: openapi-generator writes a single class holding every member's
        // properties.
        assertThat(properties("Composed"))
                .containsExactly("id", "href", "createdAt", "by", "state", "extra", "note");
    }

    @Test
    void flattensAComposedMemberOfAComposition() {
        // Timestamped is itself an allOf, so reaching createdAt above means the merge
        // recursed rather than stopping at the first level.
        assertThat(properties("Timestamped")).containsExactly("createdAt", "by", "state");
    }

    @Test
    void namesAnInlineObjectOnAnInlineAllOfMemberAfterTheMemberRatherThanTheSchema() {
        // The member is a schema with no name, and the generator invents one by inserting
        // AllOf. The infix carries no index, so several inline members of one schema all
        // share it. Neither oneOf nor anyOf gets an infix.
        assertThat(property("Composed", "note").type().schemaName())
                .isEqualTo("ComposedAllOfNote");
    }

    @Test
    void namesAnInlineObjectAfterTheSchemaThatDeclaredIt() {
        // 'by' is written inline on Created and arrives on Timestamped and Composed only
        // through the merge. The generator writes one class for it, CreatedBy, and types
        // all three properties with it. Naming it after the schema being merged would
        // produce TimestampedBy and ComposedBy, which nothing generates, so the stub
        // would not compile.
        assertThat(property("Created", "by").type().schemaName()).isEqualTo("CreatedBy");
        assertThat(property("Timestamped", "by").type().schemaName()).isEqualTo("CreatedBy");
        assertThat(property("Composed", "by").type().schemaName()).isEqualTo("CreatedBy");
    }

    @Test
    void nestsAnInlineEnumInEveryClassThatEndsUpWithIt() {
        // The opposite rule, and the reason the two hints differ: an inline enum is not
        // shared. The generator nests a copy in each class, so here the name follows the
        // schema being merged rather than the one that declared the property.
        assertThat(property("Created", "state").type().declaringSchema()).isEqualTo("Created");
        assertThat(property("Timestamped", "state").type().declaringSchema())
                .isEqualTo("Timestamped");
        assertThat(property("Composed", "state").type().declaringSchema()).isEqualTo("Composed");
    }

    // ── references outside components/schemas ─────────────────────────────────

    @Test
    void followsAReferenceToASharedResponse() {
        // swagger-parser leaves these alone even with resolution on, so an unfollowed
        // reference silently loses the response body.
        assertThat(response("getComposed", 400).schemaName()).isEqualTo("Problem");
    }

    @Test
    void followsAReferenceToASharedRequestBody() {
        assertThat(operation("postInline").requestBody().schemaName())
                .isEqualTo("PostInlineRequest");
    }

    @Test
    void followsAReferenceToASharedParameter() {
        assertThat(operation("getComposed").parametersIn(ParameterLocation.QUERY))
                .extracting(Parameter::name)
                .containsExactly("cursor");
    }

    // ── schemas written out in place ──────────────────────────────────────────

    @Test
    void namesAnInlineBodyAfterWhereItSits() {
        // openapi-generator generates a class for this same schema and calls it exactly
        // this, so any other name refers to nothing.
        assertThat(response("postInline", 200).schemaName()).isEqualTo("PostInline200Response");
        assertThat(properties("PostInline200Response")).containsExactly("message", "origin");
    }

    @Test
    void namesAnInlinePropertyAfterTheSchemaThatHoldsIt() {
        assertThat(property("PostInline200Response", "origin").type().schemaName())
                .isEqualTo("PostInline200ResponseOrigin");
    }

    @Test
    void givesOneClassToTheSameShapeWrittenTwice() {
        // The generator writes RepeatedHere once and types both properties with it. A
        // class called RepeatedAgain is a name nothing satisfies.
        assertThat(property("Repeated", "here").type().schemaName()).isEqualTo("RepeatedHere");
        assertThat(property("Repeated", "again").type().schemaName()).isEqualTo("RepeatedHere");
        assertThat(api.schemas()).doesNotContainKey("RepeatedAgain");
    }

    @Test
    void sharesThatClassAcrossSchemas() {
        assertThat(property("RepeatedElsewhere", "somewhere").type().schemaName())
                .isEqualTo("RepeatedHere");
        assertThat(api.schemas()).doesNotContainKey("RepeatedElsewhereSomewhere");
    }

    @Test
    void namesThatClassAfterTheBodyWhenTheBodyIsWrittenFirst() {
        // The generator reads the paths before the components, so a body written out in
        // place claims the name over a property written out the same way.
        assertThat(property("Repeated", "fromBody").type().schemaName())
                .isEqualTo("PostRepeatedRequest");
        assertThat(api.schemas()).doesNotContainKey("RepeatedFromBody");
    }

    @Test
    void tellsApartShapesWrittenDifferently() {
        // A description and an order of properties each make a shape of its own, however
        // alike the two read.
        assertThat(property("Repeated", "described").type().schemaName())
                .isEqualTo("RepeatedDescribed");
        assertThat(property("Repeated", "reordered").type().schemaName())
                .isEqualTo("RepeatedReordered");
    }

    // ── names that are not classes ────────────────────────────────────────────
    @Test
    void resolvesANamedArrayToTheArrayRatherThanToAClass() {
        // IdentifiedList is a name for an array. No class by that name is ever generated.
        TypeRef many = property("Aliases", "many").type();
        assertThat(many.kind()).isEqualTo(TypeRef.Kind.ARRAY);
        assertThat(many.items().schemaName()).isEqualTo("Identified");
        assertThat(api.schemas()).doesNotContainKey("IdentifiedList");
    }

    @Test
    void resolvesANamedPrimitiveToThePrimitive() {
        assertThat(property("Aliases", "flag").type().openApiType()).isEqualTo("boolean");
    }

    @Test
    void resolvesACompositionOfOneReferenceToThatReference() {
        // How a specification hangs a description on a $ref. It describes no new type and
        // the generator writes no new class.
        assertThat(property("Aliases", "described").type().schemaName()).isEqualTo("Identified");
        assertThat(api.schemas()).doesNotContainKey("AliasesDescribed");
    }

    // ── enums ─────────────────────────────────────────────────────────────────

    @Test
    void namesAnInlineEnumAfterThePropertyItBelongsTo() {
        TypeRef method = property("Enums", "method").type();
        assertThat(method.kind()).isEqualTo(TypeRef.Kind.ENUM);
        assertThat(method.declaringSchema()).isEqualTo("Enums");
        assertThat(method.schemaName()).isEqualTo("MethodEnum");
    }

    @Test
    void addsTheEnumSuffixBlindly() {
        // statusEnum becomes StatusEnumEnum. Ugly, and what the generator does.
        assertThat(property("Enums", "statusEnum").type().schemaName()).isEqualTo("StatusEnumEnum");
    }

    @Test
    void namesTheEnumInsideAnArrayAfterThePropertyAndNotTheElement() {
        // ManyEnum, not ManyInnerEnum: entering an array renames an inline object but not
        // an inline enum.
        TypeRef many = property("Enums", "many").type();
        assertThat(many.kind()).isEqualTo(TypeRef.Kind.ARRAY);
        assertThat(many.items().schemaName()).isEqualTo("ManyEnum");
        assertThat(many.items().declaringSchema()).isEqualTo("Enums");
    }

    @Test
    void leavesADeclaredEnumWithItsOwnName() {
        TypeRef named = property("Enums", "named").type();
        assertThat(named.kind()).isEqualTo(TypeRef.Kind.ENUM);
        assertThat(named.schemaName()).isEqualTo("NamedEnum");
        assertThat(named.declaringSchema()).isNull();
    }

    // ── readOnly ──────────────────────────────────────────────────────────────

    @Test
    void marksAPropertyTheModelWillHaveNoSetterFor() {
        assertThat(property("ReadOnlyHolder", "plain").readOnly()).isFalse();
        assertThat(property("ReadOnlyHolder", "frozen").readOnly()).isTrue();
    }

    @Test
    void inheritsReadOnlyThroughAReference() {
        // Said once on the schema and true of everything pointing at it.
        assertThat(property("ReadOnlyHolder", "viaRef").readOnly()).isTrue();
    }

    @Test
    void inheritsReadOnlyFromACompositionWrapper() {
        Property frozen = property("ReadOnlyHolder", "frozenObject");
        assertThat(frozen.readOnly()).isTrue();
        assertThat(frozen.type().schemaName()).isEqualTo("Identified");
    }

    // ── oneOf and anyOf ───────────────────────────────────────────────────────

    @Test
    void readsAOneOfOfASingleMemberAsThatMember() {
        // The two generator versions disagree: 7.9.0 writes a flattened class of its own,
        // 7.24.0 resolves it to the member. Reading it as the member is the only reading
        // that compiles under both, since 7.9.0 emits the member class as well.
        assertThat(api.schemas()).doesNotContainKey("BaseEvent");
        assertThat(response("getAlternatives", 200).schemaName()).isEqualTo("ChangeEvent");
    }

    @Test
    void keepsTheLastMemberWhereAlternativesDisagree() {
        // Two members, which both versions flatten into one class. payload is a string in
        // one and an integer in the other; the generator resolves that in favour of the
        // last member, so this has to as well.
        assertThat(properties("EitherEvent"))
                .containsExactly("eventType", "payload", "extra");
        assertThat(property("EitherEvent", "payload").type().openApiType())
                .isEqualTo("integer");
    }

    @Test
    void takesACompositionOfScalarsWhole() {
        // Folding the members finds no properties at all. The generator agrees, writing
        // the class with no fields.
        assertThat(api.schemas()).doesNotContainKey("Any");
        assertThat(warnings).anySatisfy(warning -> assertThat(warning)
                .contains("Any", "resolved to no properties at all"));
    }

    @Test
    void takesEveryCompositionWholeWhenToldTheyAreOpaque() {
        // Required with useOneOfInterfaces=true, under which the generator writes an empty
        // interface with no setters for merged accessors to call. That flag belongs to the
        // other tool and this one cannot see it, so it has to be told.
        List<String> opaqueWarnings = new ArrayList<>();
        StubApi opaque = new OpenApiReader(opaqueWarnings::add, Composition.OPAQUE)
                .read(Fixtures.compositionApi());

        assertThat(opaque.schemas()).doesNotContainKey("BaseEvent");
        assertThat(opaque.schemas()).doesNotContainKey("EitherEvent");
        assertThat(opaqueWarnings).anySatisfy(warning -> assertThat(warning)
                .contains("EitherEvent", "read as opaque"));
        // The allOf next door is untouched by the choice.
        assertThat(opaque.schemas()).containsKey("Composed");
    }

    @Test
    void stillReadsASingleAlternativeAsThatAlternativeWhenTheRestIsOpaque() {
        // Under useOneOfInterfaces the generator writes no interface for a composition
        // naming one alternative either, so the composition's own name refers to nothing.
        // Being opaque is about there being a choice to make, and here there is none.
        List<String> opaqueWarnings = new ArrayList<>();
        StubApi opaque = new OpenApiReader(opaqueWarnings::add, Composition.OPAQUE)
                .read(Fixtures.compositionApi());

        TypeRef body = opaque.operations().stream()
                .filter(candidate -> candidate.operationId().equals("getAlternatives"))
                .findFirst().orElseThrow()
                .responses().stream()
                .filter(response -> Integer.valueOf(200).equals(response.statusCode()))
                .findFirst().orElseThrow()
                .body();

        assertThat(body.schemaName()).isEqualTo("ChangeEvent");
        assertThat(opaqueWarnings).noneSatisfy(warning ->
                assertThat(warning).contains("BaseEvent"));
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    /**
     * A free-form bag is a map, but only when it says so. Both spellings arrive as an
     * object with no properties, and the only thing telling them apart is a boolean that
     * is not a schema -- so a reader looking for a schema sees neither and calls both
     * Object, which is right for one of them and does not compile for the other.
     */
    @Test
    void readsABooleanAdditionalPropertiesAsAMapOfAnything() {
        assertThat(property("Problem", "errorParams").type())
                .isEqualTo(TypeRef.map(TypeRef.unknown()));
        assertThat(property("Problem", "params").type().kind())
                .isEqualTo(TypeRef.Kind.UNKNOWN);
    }

    /**
     * A query parameter given an object schema is a grouping in the specification, not on
     * the wire: the client sends one parameter per property and nothing named after the
     * object. A stub that took the object at its word would wait for a parameter that is
     * never sent, and no request would ever match it.
     */
    @Test
    void expandsAnObjectQueryParameterIntoTheParametersActuallySent() {
        List<Parameter> query = operation("getGrouped").parametersIn(ParameterLocation.QUERY);

        assertThat(query).extracting(Parameter::name)
                .containsExactly("term", "limit", "kind", "tags", "Composed", "written",
                        "repeated", "joined", "spaced", "piped", "deep")
                .doesNotContain("Filter", "Inline");
        // The properties keep the types the model class gives them, so an inline enum is
        // still the enum the generator nested in the model rather than a bare string.
        assertThat(query).extracting(Parameter::type).startsWith(
                TypeRef.primitive("string", null),
                TypeRef.primitive("integer", "int64"),
                TypeRef.nestedEnumeration("Filter", "KindEnum"),
                TypeRef.array(TypeRef.primitive("string", null)),
                TypeRef.object("Composed"),
                TypeRef.primitive("string", null));
    }

    /**
     * Only a query parameter is expanded. An object sent as a header travels whole, so a
     * stub expanding it would match on headers the client never sets.
     */
    @Test
    void leavesAnObjectOutsideTheQueryStringWhole() {
        assertThat(operation("getGrouped").parametersIn(ParameterLocation.HEADER))
                .extracting(Parameter::name)
                .containsExactly("Header", "HeaderList");
    }

    private static List<String> properties(String schema) {        return schema(schema).properties().stream().map(Property::name).toList();
    }

    @Test
    void writesEachListTheWayTheGeneratedClientPutsItOnTheWire() {
        // Measured against openapi-generator 7.24.0: only explode: false comma-joins a
        // query list, a style outranks explode, and outside the query string everything
        // is comma-joined. Getting this wrong compiles and then quietly never matches.
        assertThat(collectionFormat("repeated")).isEqualTo(CollectionFormat.MULTI);
        assertThat(collectionFormat("joined")).isEqualTo(CollectionFormat.CSV);
        assertThat(collectionFormat("spaced")).isEqualTo(CollectionFormat.SSV);
        assertThat(collectionFormat("piped")).isEqualTo(CollectionFormat.PIPES);
        assertThat(collectionFormat("deep")).isEqualTo(CollectionFormat.CSV);
        assertThat(collectionFormat("HeaderList")).isEqualTo(CollectionFormat.CSV);
        assertThat(collectionFormat("cookieList")).isEqualTo(CollectionFormat.CSV);

        // A list reached by expanding a wrapper object is passed with no collection
        // format at all, and the client falls back to comma-joining it.
        assertThat(collectionFormat("tags")).isEqualTo(CollectionFormat.CSV);

        // Everything that is not a list joins nothing, whatever style it was given.
        assertThat(collectionFormat("term")).isEqualTo(CollectionFormat.NONE);
        assertThat(collectionFormat("Composed")).isEqualTo(CollectionFormat.NONE);
    }

    private static CollectionFormat collectionFormat(String parameterName) {
        return operation("getGrouped").parameters().stream()
                .filter(parameter -> parameter.name().equals(parameterName))
                .findFirst()
                .orElseThrow(() -> new AssertionError("getGrouped has no parameter " + parameterName))
                .collectionFormat();
    }

    private static Property property(String schema, String name) {
        return schema(schema).property(name)
                .orElseThrow(() -> new AssertionError(schema + " has no property " + name));
    }

    private static ObjectSchema schema(String name) {
        ObjectSchema schema = api.schemas().get(name);
        if (schema == null) {
            throw new AssertionError("no schema " + name + ", only " + api.schemas().keySet());
        }
        return schema;
    }

    private static Operation operation(String operationId) {
        return api.operations().stream()
                .filter(candidate -> candidate.operationId().equals(operationId))
                .findFirst()
                .orElseThrow(() -> new AssertionError("no operation " + operationId));
    }

    private static TypeRef response(String operationId, int code) {
        return responseOf(operationId, code).body();
    }

    private static io.github.valentinkarnaukhov.wiremockstubgen.spec.Response responseOf(String operationId, int code) {
        return operation(operationId).responses().stream()
                .filter(response -> Integer.valueOf(code).equals(response.statusCode()))
                .findFirst()
                .orElseThrow(() -> new AssertionError(operationId + " has no response " + code));
    }
}
