package io.github.valentinkarnaukhov.wiremockstubgen.openapi;

import io.github.valentinkarnaukhov.wiremockstubgen.fixtures.Fixtures;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.ObjectSchema;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Operation;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Parameter;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.ParameterLocation;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.Property;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.StubApi;
import io.github.valentinkarnaukhov.wiremockstubgen.spec.TypeRef;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Checks the reader against a specification written the way large real ones are.
 *
 * <p>Every expectation here was read off models generated by openapi-generator 7.9.0 and
 * 7.24.0, which agree. That is what makes them worth asserting: a stub names the classes
 * that generator writes, so a rule this reader gets wrong does not produce a worse stub,
 * it produces one that does not compile.
 *
 * <p>All six rules arrived together, after a real specification of 93 schemas and 23
 * operations read as <em>zero</em> usable schemas without a single warning.
 */
class OpenApiCompositionTest {

    private static StubApi api;
    private static List<String> warnings;

    @BeforeAll
    static void readFixture() {
        warnings = new ArrayList<>();
        api = new OpenApiReader(warnings::add).read(Fixtures.compositionApi());
    }

    @Test
    void readsTheWholeDocumentComplainingOnlyWhereItShould() {
        assertThat(api.operations()).hasSize(6);
        // The one thing here that genuinely describes no shape is the anyOf of scalars,
        // and saying so out loud is the designed behaviour rather than a shortcoming.
        assertThat(warnings).singleElement().asString()
                .contains("Any", "resolved to no properties at all");
    }

    // ── allOf ─────────────────────────────────────────────────────────────────

    @Test
    void flattensAllOfIntoOneSchemaInMemberOrder() {
        // Not a subclass. openapi-generator writes a single class holding every member's
        // properties, and a stub built around an inheritance that does not exist would
        // name accessors nothing has.
        assertThat(properties("Composed"))
                .containsExactly("id", "href", "createdAt", "extra");
    }

    @Test
    void flattensAComposedMemberOfAComposition() {
        // Timestamped is itself an allOf, so reaching createdAt above means the merge
        // recursed rather than stopping at the first level.
        assertThat(properties("Timestamped")).containsExactly("createdAt");
    }

    // ── references outside components/schemas ─────────────────────────────────

    @Test
    void followsAReferenceToASharedResponse() {
        // swagger-parser leaves these alone even with resolution on. Before this was
        // followed, 121 of one real specification's 154 responses were silently bodyless.
        assertThat(response("getComposed", 400).schemaName()).isEqualTo("Problem");
    }

    @Test
    void followsAReferenceToASharedRequestBody() {
        assertThat(operation("postInline").requestBody().schemaName())
                .isEqualTo("PostInlineRequest");
    }

    @Test
    void followsAReferenceToASharedParameter() {
        assertThat(operation("getComposed").parametersIn(ParameterLocation.QUERY))
                .extracting(Parameter::name)
                .containsExactly("cursor");
    }

    // ── schemas written out in place ──────────────────────────────────────────

    @Test
    void namesAnInlineBodyAfterWhereItSits() {
        // The name is the point: openapi-generator generates a class for this same schema
        // and calls it exactly this, so any other name refers to nothing.
        assertThat(response("postInline", 200).schemaName()).isEqualTo("PostInline200Response");
        assertThat(properties("PostInline200Response")).containsExactly("message", "origin");
    }

    @Test
    void namesAnInlinePropertyAfterTheSchemaThatHoldsIt() {
        assertThat(property("PostInline200Response", "origin").type().schemaName())
                .isEqualTo("PostInline200ResponseOrigin");
    }

    // ── names that are not classes ────────────────────────────────────────────

    @Test
    void resolvesANamedArrayToTheArrayRatherThanToAClass() {
        // IdentifiedList is a name for an array. No class by that name is ever generated.
        TypeRef many = property("Aliases", "many").type();
        assertThat(many.kind()).isEqualTo(TypeRef.Kind.ARRAY);
        assertThat(many.items().schemaName()).isEqualTo("Identified");
        assertThat(api.schemas()).doesNotContainKey("IdentifiedList");
    }

    @Test
    void resolvesANamedPrimitiveToThePrimitive() {
        assertThat(property("Aliases", "flag").type().openApiType()).isEqualTo("boolean");
    }

    @Test
    void resolvesACompositionOfOneReferenceToThatReference() {
        // How a specification hangs a description on a $ref, which JSON Schema forbids
        // directly. It describes no new type and the generator writes no new class.
        assertThat(property("Aliases", "described").type().schemaName()).isEqualTo("Identified");
        assertThat(api.schemas()).doesNotContainKey("AliasesDescribed");
    }

    // ── enums ─────────────────────────────────────────────────────────────────

    @Test
    void namesAnInlineEnumAfterThePropertyItBelongsTo() {
        TypeRef method = property("Enums", "method").type();
        assertThat(method.kind()).isEqualTo(TypeRef.Kind.ENUM);
        assertThat(method.declaringSchema()).isEqualTo("Enums");
        assertThat(method.schemaName()).isEqualTo("MethodEnum");
    }

    @Test
    void addsTheEnumSuffixBlindly() {
        // statusEnum becomes StatusEnumEnum. Ugly, and what the generator does, which is
        // the only thing that matters here.
        assertThat(property("Enums", "statusEnum").type().schemaName()).isEqualTo("StatusEnumEnum");
    }

    @Test
    void namesTheEnumInsideAnArrayAfterThePropertyAndNotTheElement() {
        // ManyEnum, not ManyInnerEnum: entering an array renames an inline object but not
        // an inline enum.
        TypeRef many = property("Enums", "many").type();
        assertThat(many.kind()).isEqualTo(TypeRef.Kind.ARRAY);
        assertThat(many.items().schemaName()).isEqualTo("ManyEnum");
        assertThat(many.items().declaringSchema()).isEqualTo("Enums");
    }

    @Test
    void leavesADeclaredEnumWithItsOwnName() {
        TypeRef named = property("Enums", "named").type();
        assertThat(named.kind()).isEqualTo(TypeRef.Kind.ENUM);
        assertThat(named.schemaName()).isEqualTo("NamedEnum");
        assertThat(named.declaringSchema()).isNull();
    }

    // ── readOnly ──────────────────────────────────────────────────────────────

    @Test
    void marksAPropertyTheModelWillHaveNoSetterFor() {
        assertThat(property("ReadOnlyHolder", "plain").readOnly()).isFalse();
        assertThat(property("ReadOnlyHolder", "frozen").readOnly()).isTrue();
    }

    @Test
    void inheritsReadOnlyThroughAReference() {
        // Said once on the schema and true of everything pointing at it, which is how the
        // real specification wrote it.
        assertThat(property("ReadOnlyHolder", "viaRef").readOnly()).isTrue();
    }

    @Test
    void inheritsReadOnlyFromACompositionWrapper() {
        Property frozen = property("ReadOnlyHolder", "frozenObject");
        assertThat(frozen.readOnly()).isTrue();
        assertThat(frozen.type().schemaName()).isEqualTo("Identified");
    }

    // ── oneOf and anyOf ───────────────────────────────────────────────────────

    @Test
    void readsAOneOfOfASingleMemberAsThatMember() {
        // The two generator versions disagree here: 7.9.0 writes a flattened class of its
        // own, 7.24.0 writes none and resolves it to the member. Reading it as the member
        // is the only reading that compiles under both, because 7.9.0 emits the member
        // class as well while the flattened name exists in 7.9.0 alone.
        assertThat(api.schemas()).doesNotContainKey("BaseEvent");
        assertThat(response("getAlternatives", 200).schemaName()).isEqualTo("ChangeEvent");
    }

    @Test
    void keepsTheLastMemberWhereAlternativesDisagree() {
        // Two members, which both versions do flatten into one class. payload is a string
        // in one and an integer in the other, and the generator resolves that silently in
        // favour of the last member, so this has to as well: agreeing with it matters more
        // than being right.
        assertThat(properties("EitherEvent"))
                .containsExactly("eventType", "payload", "extra");
        assertThat(property("EitherEvent", "payload").type().openApiType())
                .isEqualTo("integer");
    }

    @Test
    void takesACompositionOfScalarsWhole() {
        // Nothing to accessor here, and no special case needed to say so: folding the
        // members finds no properties at all. The generator agrees, writing the class
        // with no fields.
        assertThat(api.schemas()).doesNotContainKey("Any");
        assertThat(warnings).anySatisfy(warning -> assertThat(warning)
                .contains("Any", "resolved to no properties at all"));
    }

    @Test
    void takesEveryCompositionWholeWhenToldTheyAreOpaque() {
        // Required with useOneOfInterfaces=true, under which the generator writes an empty
        // interface: there would be no setters for merged accessors to call. The flag
        // belongs to the other tool and this one cannot see it, so it has to be told.
        List<String> opaqueWarnings = new ArrayList<>();
        StubApi opaque = new OpenApiReader(opaqueWarnings::add, Composition.OPAQUE)
                .read(Fixtures.compositionApi());

        assertThat(opaque.schemas()).doesNotContainKey("BaseEvent");
        assertThat(opaque.schemas()).doesNotContainKey("EitherEvent");
        assertThat(opaqueWarnings).anySatisfy(warning -> assertThat(warning)
                .contains("EitherEvent", "read as opaque"));
        // The allOf next door is untouched by the choice.
        assertThat(opaque.schemas()).containsKey("Composed");
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private static List<String> properties(String schema) {
        return schema(schema).properties().stream().map(Property::name).toList();
    }

    private static Property property(String schema, String name) {
        return schema(schema).property(name)
                .orElseThrow(() -> new AssertionError(schema + " has no property " + name));
    }

    private static ObjectSchema schema(String name) {
        ObjectSchema schema = api.schemas().get(name);
        if (schema == null) {
            throw new AssertionError("no schema " + name + ", only " + api.schemas().keySet());
        }
        return schema;
    }

    private static Operation operation(String operationId) {
        return api.operations().stream()
                .filter(candidate -> candidate.operationId().equals(operationId))
                .findFirst()
                .orElseThrow(() -> new AssertionError("no operation " + operationId));
    }

    private static TypeRef response(String operationId, int code) {
        return operation(operationId).responses().stream()
                .filter(response -> Integer.valueOf(code).equals(response.statusCode()))
                .findFirst()
                .orElseThrow(() -> new AssertionError(operationId + " has no response " + code))
                .body();
    }
}
